alias activate='source .venv/bin/activate'
alias cta='ct --pcre screen -R -D'
alias g='grep -E -i'
alias h=history
alias l='ls -AlgGhd .* 2>/dev/null'
alias la='ls -a'
alias ll='ls -lgGh'
alias lla='ls -AlgGh'
alias ls='ls --color=auto -F'
alias m='less -XRF'
alias mv='mv -i'
alias rm='rm -i'
alias scrls='screen -list'
alias vi='vim -u NONE -U NONE'

# git
alias ga='git add'
alias gaa='git add --all'
alias gc!='git commit -v --amend'
alias gcam='git commit -a -m'
alias gcmsg='git commit -m'
alias gcp='git commit --patch'
alias gd='git diff'
alias gl='git pull'
alias glog='git log --oneline --decorate --color --graph'
alias gpr='git pull --rebase'
alias gp='git push'
alias gst='git status'

