alias activate='source .venv/bin/activate'
alias batfish='docker run -d --name batfish -v batfish-data:/data -p 8888:8888 -p 9997:9997 -p 9996:9996 batfish/allinone'
alias brave='flatpak run com.brave.Browser'
alias cta='ct --pcre screen -R -D'
alias cts='ct --pcre screen -R -D'
alias firefox='flatpak run org.mozilla.firefox'
alias flatpak='flatpak --user'
alias g='grep -E -i'
alias gimp='flatpak run org.gimp.GIMP'
alias inkscape='flatpak run org.inkscape.Inkscape'
alias krita='flatpak run org.kde.krita'
alias l='ls -AlgGhd .* 2>/dev/null'
alias la='ls -a'
alias libreoffice='flatpak run org.libreoffice.LibreOffice'
alias ll='ls -lgGh'
alias lla='ls -AlgGh'
alias ls='ls --color=auto -F'
alias m='less -XRF'
alias mv='mv -i'
alias pycharm='flatpak run com.jetbrains.PyCharm-Professional'
alias rm='rm -i'
alias scrls='screen -list'
alias vi='vim -u NONE -U NONE'
alias vivaldi='flatpak run com.vivaldi.Vivaldi'

# git
alias ga='git add'
alias gaa='git add --all'
alias gc!='git commit -v --amend'
alias gcam='git commit -a -m'
alias gcmsg='git commit -m'
alias gcp='git commit --patch'
alias gd='git diff'
alias gl='git pull'
alias glog='git log --oneline --decorate --color --graph'
alias gpr='git pull --rebase'
alias gp='git push'
alias gst='git status'
