set-option -a terminal-features 'xterm-256color:RGB'
set-option -g focus-events on
set-option -s set-clipboard
set-option -sg escape-time 10
set-window-option -g mode-keys vi
bind %   split-window -v -c "#{pane_current_path}"
bind '"' split-window -h -c "#{pane_current_path}"
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi v   send-keys -X begin-selection
bind -T copy-mode-vi y   send-keys -X copy-selection-and-cancel
bind -n M-Down select-pane -D
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind C-d detach-client
bind K kill-pane
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind x detach-client -a
