set -a terminal-features 'xterm-256color:RGB'
set -g @logging-filename "#W_logging_%Y%m%dT%H%M%S.log"
set -g @logging-path "$HOME/logs"
set -g @save-complete-history-filename "#W_%Y%m%dT%H%M%S.log"
set -g @save-complete-history-path "$HOME/logs"
set -g @screen-capture-filename "#W_screencap_%Y%m%dT%H%M%S.log"
set -g @screen-capture-path "$HOME/logs"

set -g focus-events on
set -g history-limit 100000
set -g mouse off
set -g remain-on-exit on
set -g status-style bg=default
set -g window-status-current-style bg=red,fg=black
set -g window-status-style bg=default
set -s set-clipboard on
set -sg escape-time 10

## status format
set -g status-right '#{prefix_highlight} | %a %Y-%m-%d %H:%M'
set -Fg 'status-format[1]' '#{status-format[0]}'
set -g 'status-format[0]' ''
set -g status 2

bind %   split-window -v -c "#{pane_current_path}"
bind '"' split-window -h -c "#{pane_current_path}"
bind C-d detach-client
bind K kill-pane
bind C-k kill-pane
bind r respawn-pane
bind x detach-client -a

## vi
set-window-option -g mode-keys vi
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -T copy-mode-vi v   send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind -T copy-mode-vi y   send-keys -X copy-selection-and-cancel

set -g @save-complete-history-key 'C-p'
# git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-prefix-highlight'
set -g @plugin 'tmux-plugins/tmux-yank'

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.config/tmux/plugins/tpm/tpm'
# vim:ft=tmux
