set nocompatible
filetype off

call plug#begin("~/.config/vim/plugged")
Plug 'tpope/vim-commentary'
Plug 'junegunn/vim-easy-align'
Plug 'tpope/vim-endwise'
Plug 'tpope/vim-repeat'
Plug 'tpope/vim-rsi'
Plug 'kshenoy/vim-signature'
Plug 'tpope/vim-surround'
Plug 'sonph/onehalf', { 'rtp': 'vim' }
Plug 'axvr/photon.vim'
Plug 'ojroques/vim-oscyank', {'branch': 'main'}
Plug 'jeffkreeftmeijer/vim-numbertoggle'
Plug 'farmergreg/vim-lastplace'
Plug 'junegunn/fzf'
Plug 'junegunn/fzf.vim'
call plug#end()

filetype plugin indent on
syntax on

packadd! matchit

let mapleader=" "

set autoindent
set autoread
set background=dark
set writebackup
set backspace=indent,eol,start
set backup
set backupdir=~/tmp//
set belloff=all
set clipboard=unnamedplus,unnamed
set cmdheight=2
set complete+=kspell ":help cpt
set display=lastline,truncate
set encoding=utf-8
set expandtab
set foldcolumn=2
set formatoptions=croqlj
set hidden
set hlsearch
set history=1000
set ignorecase
set incsearch
set infercase
set nolangremap
set laststatus=2
set list
set listchars=tab:»·,trail:·
set mouse=
set nrformats-=octal
set number relativenumber
set pastetoggle=<F12>
set ruler
set scrolloff=1
set sessionoptions-=options
set shiftwidth=4
set showmode
set showtabline=2
set sidescroll=1
set sidescrolloff=2
set signcolumn=yes
set smartcase
set smartindent
set smarttab
set softtabstop=4
set tabpagemax=50
set tabstop=4
set termguicolors
set textwidth=80
set ttimeout
set ttimeoutlen=100
set undofile
set undodir=~/.config/vim//
set viewoptions-=options
set viminfo=!,'1000,n~/.config/vim/
set viminfofile=~/.config/vim/.viminfo
set wildmenu

" from 'tpope/vim-sensible'
" Replace the check for a tags file in the parent directory of the current
" file with a check in every ancestor directory.
if has('path_extra') && (',' . &g:tags . ',') =~# ',\./tags,'
  setglobal tags-=./tags tags-=./tags; tags^=./tags;
endif

map Q                     gq
nnoremap <silent> <C-L>   :nohlsearch<CR>
inoremap <C-U>            <C-G>u<C-U>
nnoremap U                :redo<CR>
nnoremap Y                y$
nnoremap /                /\v
nnoremap ?                ?\v
vnoremap <                <gv
vnoremap >                >gv
inoremap <silent> ;;d     ============<C-R>=strftime("%Y-%m-%d %H:%M:%S")<CR>============<CR>
inoremap <silent> ;;l     -------------------------------------------<CR>

" plugin related maps

if exists('$SSH_TTY')
  vnoremap <leader>y      :OSCYankVisual<CR>
  nnoremap <leader>Y      v$:OSCYankVisual<CR>
  nnoremap <leader>yy     V:OSCYankVisual<CR>
else
  vnoremap <leader>y      "+y
  nnoremap <leader>Y      "+y
  nnoremap <leader>yy     "+Y
endif

vnoremap <Enter>          <Plug>(EasyAlign)
noremap ga                <Plug>(EasyAlign)

colorscheme onehalfdark
highlight clear foldcolumn
highlight clear signcolumn
highlight clear Tablinefill
set statusline=%<%f%=\ [%1*%M%*%{','.&fileformat}%R%Y]\ [%6l,%4c%V]\ %3b\ 0x%02Bh\ %P
" vim:ft=vim:tw=0:sw=2:ts=2:sts=2:nowrap
